# Exercise

1. Find the values of
\[    (1 + 2i)^3, \quad \frac{5}{-3 + 4i}, \quad \left( \frac{2 + i}{3 - 2i} \right)^2, \quad (1 + i)^n + (1 - i)^n.\]

1. If \( z = x + iy \) (where \(x\) and \(y\) are real numbers), find the real and imaginary parts of:
\[z^4, \quad \frac{1}{z}, \quad \frac{z - 1}{z + 1}, \quad \frac{1}{z^2}.\]
    
1. Show that:
\[  \left( \frac{-1 \pm i\sqrt{3}}{2} \right)^3 = 1 \quad \text{and} \quad \left( \frac{\pm 1 \pm i\sqrt{3}}{2} \right)^6 = 1\]
for all combinations of signs.


# Green functions
 Let $G$ be a reigon and $a\in G$. Green functions $G$ with singularity at $a$, the unique function $g_a:G\setminus \{0\}$ 
 
 1. $g_a$ is harmonisc on $G\setminus\{a\}.
 2. $g_a(z)+\log(|z-a|)$ is harmonic^[has an exteror to $u$. ($a\in u$) , $u$ is open in $G$.] on an open neighbourhood of $a$.
 3. $\lim_{z\to w}g_a(z)=0 ~~~\forall w \in \partial_\infty G$.
 
 ```{remark}
 $g_a(z)>0$ for all $z \in G\setminus \{a\}$ because $g_a(z)+\log(|z-a|)$ has contious externsion to $u$ and $$\lim_{z\to w}g_a(z)=-\infty$
 ```
 
 We have $g_a(z)0$ on $|z-a|=r$ for $r$ small enough (then there exist $R$ such that its positive $\forall r<R$) Given $r<R$ such that $z_0$ is $|z-a|=r$. Apply max principle on $G\setminus\{z:|z-a|\leq r\}$. Since $g_a(z)\geq 0$ or $\$
 